config/routes.rb
StudentManage::Application.routes.draw do

  resources :news, only: [:index, :show]

  namespace :admin do
    get "home" => "home#index"
    resources :zhuanyes
    resources :application_dates
    resources :news
    resources :applications
    resources :users
    resources :xueyuans
  end

  namespace :xuegongchu do
    get "home" => "home#index"
    resources :reward_applications, only: [:index, :show] do
      member do
        get :change
      end
    end
  end

  namespace :student do
    resources :reward_applications do
      member do
        get :change
        post :toupiao
      end
      collection do
        get :other
      end
    end
    resources :person_infos, except: [:index, :destroy]
    get "home" => "home#index"
    resources :scores
  end

  devise_for :users
  get "" => "home#index", as: "home"
  root to: "home#index"
end

app/views/shared/_admin_left.html.erb
<div class="main-container" id="main-container">
  <script type="text/javascript">
    try{ace.settings.check('main-container' , 'fixed')}catch(e){}
  </script>

  <div class="main-container-inner">
    <a class="menu-toggler" id="menu-toggler" href="#">
      <span class="menu-text"></span>
    </a>

    <div class="sidebar" id="sidebar">
      <script type="text/javascript">
        try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
      </script>

      <div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
          <%= link_to_icon "icon-home", '', home_path, class: "btn btn-success" %>
          <%= link_to_icon "icon-user", '', admin_home_path, class: "btn btn-info" %>
          <%= link_to_icon "icon-key", '', edit_user_registration_path, class: "btn btn-warning" %>
          <%= link_to_icon "icon-off", '', destroy_user_session_path, class: "btn btn-danger", method: :delete %>
        </div>

      </div><!-- #sidebar-shortcuts -->

      <ul class="nav nav-list">

        <% if current_user.admin? %>
          <li id="admin_home">
            <%= link_to admin_home_path do %>
              <i class="icon-user"></i>
              <span class="menu-text"> 后台管理首页 </span>
            <% end %>
          </li>

          <li id="admin_user">
            <%= link_to admin_users_path do %>
              <i class="icon-list"></i>
              <span class="menu-text"> 用户管理 </span>
            <% end %>
          </li>

          <li id="admin_news">
            <%= link_to admin_news_index_path do %>
              <i class="icon-list"></i>
              <span class="menu-text"> 公告管理 </span>
            <% end %>
          </li>

          <li id="admin_xueyuan">
            <%= link_to admin_xueyuans_path do %>
              <i class="icon-list"></i>
              <span class="menu-text"> 学院管理 </span>
            <% end %>
          </li>

          <li id="admin_zhuanye">
            <%= link_to admin_zhuanyes_path do %>
              <i class="icon-list"></i>
              <span class="menu-text"> 专业管理 </span>
            <% end %>
          </li>

          <li id="admin_application">
            <%= link_to admin_applications_path do %>
              <i class="icon-list"></i>
              <span class="menu-text"> 评优奖励管理 </span>
            <% end %>
          </li>

          <li id="admin_application_date">
            <%= link_to new_admin_application_date_path do %>
              <i class="icon-list"></i>
              <span class="menu-text"> 时间阶段管理 </span>
            <% end %>
          </li>

        <% end %>

        <% if current_user.student? %>
        <li id="student_home">
          <%= link_to student_home_path do %>
            <i class="icon-user"></i>
            <span class="menu-text"> 后台管理首页 </span>
          <% end %>
        </li>
        <li id="student_score">
          <%= link_to student_scores_path do %>
            <i class="icon-list"></i>
            <span class="menu-text"> 成绩管理 </span>
          <% end %>
        </li>
        <li id="student_reward_application">
          <%= link_to student_reward_applications_path do %>
            <i class="icon-list"></i>
            <span class="menu-text"> 评优奖励申请 </span>
          <% end %>
        </li>

        <li id="other_student_reward_application">
          <%= link_to other_student_reward_applications_path do %>
            <i class="icon-list"></i>
            <span class="menu-text"> 网上投票 </span>
          <% end %>
        </li>

        <% end %>

        <% if current_user.xuegongchu? %>
        <li id="xuegongchu_home">
          <%= link_to xuegongchu_home_path do %>
            <i class="icon-user"></i>
            <span class="menu-text"> 后台管理首页 </span>
          <% end %>
        </li>
        <li id="xuegongchu_reward_application">
          <%= link_to xuegongchu_reward_applications_path do %>
            <i class="icon-list"></i>
            <span class="menu-text"> 评优奖励申请管理 </span>
          <% end %>
        </li>
        <% end %>


      </ul><!-- /.nav-list -->

      <div class="sidebar-collapse" id="sidebar-collapse">
        <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
      </div>

      <script type="text/javascript">
        try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
      </script>
    </div>

    <div class="main-content">
      <div class="breadcrumbs" id="breadcrumbs">
        <script type="text/javascript">
          try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
        </script>

        <ul class="breadcrumb">
          <%= yield :breadcrumb %>
        </ul><!-- .breadcrumb -->

      </div>
      <%= yield %>
    </div>


    </div>
    </div>

app/views/shared/_admin_top.html.erb
<div class="navbar navbar-default" id="navbar">
  <script type="text/javascript">
    try{ace.settings.check('navbar' , 'fixed')}catch(e){}
  </script>

  <div class="navbar-container" id="navbar-container">
    <div class="navbar-header pull-left">
      <a href="<%= home_path %>" class="navbar-brand">
        <small>
          <i class="icon-leaf"></i>
          评优管理系统
        </small>
      </a><!-- /.brand -->
    </div><!-- /.navbar-header -->


    <ul class="nav navbar-nav">
      <li id="home_page">
        <%= link_to '首页', home_path %>
      </li>
      <li id="news_page" >
        <%= link_to '公告', news_index_path %>
      </li>
    </ul>


    <div class="navbar-header pull-right" role="navigation">
      <ul class="nav ace-nav">


        <li class="light-blue">
          <% if user_signed_in? %>
            <a data-toggle="dropdown" href="#" class="dropdown-toggle">
              <%= current_user.username %>
              <i class="icon-caret-down"></i>
            </a>

            <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
              <li>
              <% if current_user.admin? %>
                <%= link_to_icon 'icon-user', "后台管理", admin_home_path %>
              <% elsif current_user.student? %>
                <%= link_to_icon 'icon-user', "后台管理", student_home_path %>
              <% elsif current_user.xuegongchu? %>
                <%= link_to_icon 'icon-user', "后台管理", xuegongchu_home_path %>
              <% end %>
              </li>
              <li>
                <%= link_to_icon "icon-key", "修改密码", edit_user_registration_path %>
              </li>

              <li>
              <% if current_user.student? %>
                <%= link_to_icon 'icon-user', "修改用户信息", new_student_person_info_path %>
              <% end %>
              </li>

              <li class="divider"></li>
              <li>
                <%= link_to_icon "icon-off", '退出', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          <% else %>
            <%= link_to '登录', new_user_session_path %>
          <% end %>
        </li>
      </ul><!-- /.ace-nav -->
    </div><!-- /.navbar-header -->
  </div><!-- /.container -->
</div>

app/views/shared/_head.html.erb
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

app/views/shared/_js.html.erb
<%= yield(:script) if content_for?(:script) %>