config/routes.rb
StudentManage::Application.routes.draw do

  resources :news, only: [:index, :show]

  namespace :admin do
    get "home" => "home#index"
    resources :zhuanyes
    resources :application_dates
    resources :news
    resources :applications
    resources :users
    resources :xueyuans
  end

  namespace :xuegongchu do
    get "home" => "home#index"
    resources :reward_applications, only: [:index, :show] do
      member do
        get :change
      end
    end
  end

  namespace :student do
    resources :reward_applications do
      member do
        get :change
        post :toupiao
      end
      collection do
        get :other
      end
    end
    resources :person_infos, except: [:index, :destroy]
    get "home" => "home#index"
    resources :scores
  end

  devise_for :users
  get "" => "home#index", as: "home"
  root to: "home#index"
end

app/models/application_date.rb
class ApplicationDate < ActiveRecord::Base
  validates_presence_of :start_at, :end_at
  validate :verify_count, on: :create
  validate :verify_end_at_gte_start_at

  protected

  def verify_count
    errors.add(:base, "只能添加一条记录") if self.class.count > 1
  end

  def verify_end_at_gte_start_at
    errors.add(:end_at, "结束时间必须大于开始时间") if start_at >= end_at
  end
end

app/controllers/admin/application_dates_controller.rb
class Admin::ApplicationDatesController < Admin::BaseController
  before_action :set_application_date, only: [:show, :edit, :update, :destroy]
  before_action :redirect_where_path, only: [:new, :edit]

  # GET /admin/application_dates
  # GET /admin/application_dates.json
  def index
    @application_dates = ApplicationDate.all
  end

  # GET /admin/application_dates/1
  # GET /admin/application_dates/1.json
  def show
  end

  # GET /admin/application_dates/new
  def new
    @application_date = ApplicationDate.new
  end

  # GET /admin/application_dates/1/edit
  def edit
  end

  # POST /admin/application_dates
  # POST /admin/application_dates.json
  def create
    @application_date = ApplicationDate.new(application_date_params)

    respond_to do |format|
      if @application_date.save
        format.html { redirect_to admin_home_path, notice: '时间阶段创建成功' }
        format.json { render action: 'show', status: :created, location: @application_date }
      else
        format.html { render action: 'new' }
        format.json { render json: @application_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/application_dates/1
  # PATCH/PUT /admin/application_dates/1.json
  def update
    respond_to do |format|
      if @application_date.update(application_date_params)
        format.html { redirect_to admin_home_path, notice: '时间阶段更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/application_dates/1
  # DELETE /admin/application_dates/1.json
  def destroy
    @application_date.destroy
    respond_to do |format|
      format.html { redirect_to application_dates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_date
      @application_date = ApplicationDate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_date_params
      params.require(:application_date).permit(:start_at, :end_at)
    end

    def redirect_where_path
      application_date = ApplicationDate.first
      if application_date.present? && params[:action] == "new"
        redirect_to edit_admin_application_date_path(application_date)
      elsif application_date.nil? && params[:action] == "edit"
        redirect_to new_application_dates_path
      end
    end

end

app/helpers/admin/application_dates_helper.rb
module Admin::ApplicationDatesHelper
end

app/views/admin/application_dates/_form.html.erb
<%= simple_form_for([:admin, @application_date], wrapper: "default-form", html: {role: "form"}) do |f| %>

  <div class="form-inputs">
    <%= f.input :start_at, label_html: {class: "col-sm-2"} %>
    <%= f.input :end_at, label_html: {class: "col-sm-2"} %>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-md-10">
      <%= f.button :submit, "保存", class: "btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/application_dates/edit.html.erb
<% content_for :breadcrumb do %>
<li>
  <i class="icon-home home-icon"></i>
  <a href="<%= home_path %>">首页</a>
</li>
<li class="active">时间阶段编辑</li>
<% end %>

<div class="page-content">
  <div class="page-header">
    <h1>
      时间阶段编辑
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <%= render "form" %>
    </div>
  </div>
</div>


<% content_for :script do %>
  <script>
    $(function(){
      $("#admin_application_date").addClass("active")
    })
  </script>
<% end %>

app/views/admin/application_dates/index.html.erb
<% content_for :breadcrumb do %>
<li>
  <i class="icon-home home-icon"></i>
  <a href="<%= home_path %>">首页</a>
</li>
<li class="active">时间阶段管理</li>
<% end %>

<div class="page-content">
  <div class="page-header">
    <h1>
      时间阶段 管理
      <small>
        <i class="icon-double-angle-right"></i>
        <%= link_to '时间阶段 添加', new_admin_application_date_path %>
      </small>
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">

    <table class="table">
      <thead>
        <tr>
          <th>Start at</th>
          <th>End at</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @application_dates.each do |application_date| %>
          <tr>
            <td><%= application_date.start_at %></td>
            <td><%= application_date.end_at %></td>
            <td><%= link_to 'Show', application_date %></td>
            <td><%= link_to 'Edit', edit_admin_application_date_path(application_date) %></td>
            <td><%= link_to 'Destroy', application_date, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    </div>
  </div>
</div>


<% content_for :script do %>
  <script>
    $(function(){
      $("#admin_application_date").addClass("active")
    })
  </script>
<% end %>

app/views/admin/application_dates/new.html.erb
<% content_for :breadcrumb do %>
<li>
  <i class="icon-home home-icon"></i>
  <a href="<%= home_path %>">首页</a>
</li>
<li class="active">时间阶段创建</li>
<% end %>

<div class="page-content">
  <div class="page-header">
    <h1>
      时间阶段创建
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <%= render "form" %>
    </div>
  </div>
</div>


<% content_for :script do %>
  <script>
    $(function(){
      $("#admin_application_date").addClass("active")
    })
  </script>
<% end %>

app/views/admin/application_dates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start at:</strong>
  <%= @application_date.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @application_date.end_at %>
</p>

<%= link_to 'Edit', edit_application_date_path(@application_date) %> |
<%= link_to 'Back', application_dates_path %>

<% content_for :script do %>
  <script>
    $(function(){
      $("#admin_application_date").addClass("active")
    })
  </script>
<% end %>