config/routes.rb
StudentManage::Application.routes.draw do

  resources :news, only: [:index, :show]

  namespace :admin do
    get "home" => "home#index"
    resources :zhuanyes
    resources :application_dates
    resources :news
    resources :applications
    resources :users
    resources :xueyuans
  end

  namespace :xuegongchu do
    get "home" => "home#index"
    resources :reward_applications, only: [:index, :show] do
      member do
        get :change
      end
    end
  end

  namespace :student do
    resources :reward_applications do
      member do
        get :change
        post :toupiao
      end
      collection do
        get :other
      end
    end
    resources :person_infos, except: [:index, :destroy]
    get "home" => "home#index"
    resources :scores
  end

  devise_for :users
  get "" => "home#index", as: "home"
  root to: "home#index"
end

app/models/reward_application.rb
class RewardApplication < ActiveRecord::Base

  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user
  belongs_to :application, class_name: :Application
  belongs_to :xueyuan, class_name: :Xueyuan

  has_many :user_reward_applications, dependent: :destroy
  has_many :users, through: :user_reward_applications

  validates_presence_of :application_id, :phone, :xueyuan_id, :content, :rongyu, :user_id, :state
  validate :verify_state

  state_machine initial: :weishangbao do
    event :shangbao do
      transition :weishangbao => :yishangbao
    end

    event :chehui do
      transition :yishangbao => :weishangbao
      transition :yishengpi => :weishangbao
    end

    event :shenpi do
      transition :yishangbao => :yishengpi
    end

    event :tongguo do
      transition :yishengpi => :yitongguo
    end

    event :jujue do
      transition :yishengpi => :yijujue
    end


    state :weishangbao, value: "未上报"
    state :yishangbao, value: "已上报"
    state :yishengpi, value: "已审批"
    state :yijujue, value: "已拒绝"
    state :yitongguo, value: "已通过"
  end

  def self.get_event_text_by(event)
    {"shangbao" => "上报", "chehui" => "撤回", "shenpi" => "审批", "tongguo" => "通过", "jujue" => "拒绝"}[event.to_s]
  end


  protected

  def verify_state
    yishangbao_reward_application = user.reward_applications.with_state(:yishangbao)
    errors.add(:base, "您已经上报了一份评优申请") if yishangbao_reward_application.present? && yishangbao?
  end

  # def verify_event
  #   errors.add(:base, "无权限此操作") if user.student? && (yishengpi? || yitongguo? || yijujue?)
  # end

end

# 上报  审批、撤回、决绝
# 新填写未上报 已上报 已审批  已拒绝

# 上报后的申请单不允许进行修改、删除
# 报后的申请单不能够进行修改和删除操作
# 撤回操作会将申请单的状态从“已上报”还原为“新填写未上报”
# 上报后的申请单如果未经审批,在申请阶段可以撤回

#问题：
#拒绝的申请，学生不能继续申请

app/controllers/student/reward_applications_controller.rb
class Student::RewardApplicationsController < Student::BaseController
  prepend_before_action :set_reward_application, only: [:show, :edit, :update, :destroy, :change]
  before_action :verify_edit_reward_application, only: :edit
  before_action :verify_application_date, only: :change


  def index
    @reward_applications = current_user.reward_applications.page(params[:page]).per_page(10)
    @yishangbao_reward_application = current_user.reward_applications.with_state(:yishangbao).first
  end

  def show
  end

  def new
    @reward_application = current_user.reward_applications.new
  end

  def edit
  end

  def create
    @reward_application = current_user.reward_applications.new(reward_application_params)

    respond_to do |format|
      if @reward_application.save
        format.html { redirect_to student_reward_applications_url, notice: '评优奖励申请开始' }
        format.json { render action: 'show', status: :created, location: @reward_application }
      else
        format.html { render action: 'new' }
        format.json { render json: @reward_application.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reward_application.update(reward_application_params)
        format.html { redirect_to student_reward_applications_url, notice: '评优奖励更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reward_application.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reward_application.destroy
    respond_to do |format|
      format.html { redirect_to student_reward_applications_url }
      format.json { head :no_content }
    end
  end

  def change
    @reward_application.send(params[:shijian].to_sym)
    redirect_to student_reward_applications_url
  end

  def other
    @reward_applications = RewardApplication.where(state: ["已审批"]).page(params[:page]).per_page(10).order("created_at DESC")
  end

  def toupiao
    @reward_application = RewardApplication.find(params[:id])
    current_user.toupiao(@reward_application)
    render json: {status: true, application_id: @reward_application.application_id}.to_json
  end

  private

    def verify_edit_reward_application
      if !(@reward_application.weishangbao? || @reward_application.yishangbao?)
        redirect_to student_reward_applications_url, notice: "#{@reward_application.state}的申请不可以编辑"
      end
    end

    def verify_application_date
      application_date = ApplicationDate.first
      if application_date.blank? || Date.current < application_date.start_at || Date.current > application_date.end_at
        redirect_to student_home_path, notice: "评优奖励申请时间阶段尚未创建 或者 您不在该时间阶段内"
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_reward_application
      @reward_application = current_user.reward_applications.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_application_params
      params.require(:reward_application).permit(:application_id, :phone, :xueyuan_id, :content, :rongyu, :user_id)
    end
end

app/controllers/xuegongchu/base_controller.rb
class Xuegongchu::BaseController < ApplicationController

  layout "admin"
  before_action :authenticate_xuegongchu!


  protected

  def authenticate_xuegongchu!
    if !user_signed_in? || !current_user.xuegongchu?
      redirect_to home_path
    end
  end




end

app/controllers/xuegongchu/home_controller.rb
class Xuegongchu::HomeController < Xuegongchu::BaseController
  def index
    @current_date_reward_applications = RewardApplication.search(created_at_gte: Date.current, state_eq: "已上报").result
  end
end

app/controllers/xuegongchu/reward_applications_controller.rb
class Xuegongchu::RewardApplicationsController < Xuegongchu::BaseController

  def index
    params[:search].merge!(created_at_gteq: params[:search][:created_at_gteq]+"-01-01") if params[:search].try(:[], :created_at_gteq).present?
    @search = RewardApplication.where("state != ?", "未上报").search(params[:search])
    @reward_applications = @search.result.page(params[:page]).per_page(30)
  end

  def show
    @reward_application = RewardApplication.find(params[:id])
    @student_scores = @reward_application.user.scores.page(params[:page]).per_page(10)
  end

  def change
    @reward_application = RewardApplication.find(params[:id])
    @reward_application.send(params[:shijian].to_sym)
    redirect_to xuegongchu_reward_applications_url
  end


end

app/helpers/student/reward_applications_helper.rb
module Student::RewardApplicationsHelper
end

app/views/xuegongchu/reward_applications/index.html.erb
<% content_for :breadcrumb do %>
<li>
  <i class="icon-home home-icon"></i>
  <a href="<%= home_path %>">首页</a>
</li>
<li class="active">评优奖励申请管理</li>
<% end %>

<div class="page-content">
  <div class="page-header">
    <h1>
      评优奖励申请 管理
      <small>
        <i class="icon-double-angle-right"></i>
        <%= link_to '申请评优奖励', new_student_reward_application_path %>
      </small>
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <%= form_tag xuegongchu_reward_applications_path, method: :get, class: "form-inline" do %>
        <%= select_tag "search[created_at_gteq]", options_for_select(["2014", "2015"], params[:search].try(:[], :created_at_gteq).to_s.try(:match, /\d+/)), prompt: "选择年度" %>
        <%= select_tag "search[state_eq]", options_for_select([["已上报", "已上报"], ["已审批", "已审批"], ["已拒绝", "已拒绝"], ["已通过", "已通过"]], params[:search].try(:[], :state_eq)), prompt: "选择状态" %>
        <%= select_tag "search[xueyuan_id_eq]", options_for_select(Xueyuan.pluck(:name, :id), params[:search].try(:[], :xueyuan_id_eq)), prompt: "选择学院" %>
        <%= submit_tag "搜索", class: "btn" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">

    <table class="table">
      <thead>
        <tr>
          <th>姓名</th>
          <th>性别</th>
          <th>申请奖励</th>
          <th>状态</th>
          <th>联系方式</th>
          <th>学院</th>
          <th>申请说明</th>
          <th>获得荣誉</th>
          <th>投票数</th>
          <th>年度</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @reward_applications.each do |reward_application| %>
          <% person_info = reward_application.user.person_info %>
          <tr>
            <td><%= person_info.name %></td>
            <td><%= person_info.gender.name %></td>
            <td><%= reward_application.application.try(:name) %></td>
            <td><%= reward_application.state %></td>
            <td><%= reward_application.phone %></td>
            <td><%= reward_application.xueyuan.try(:name) %></td>
            <td><%= reward_application.content %></td>
            <td><%= reward_application.rongyu %></td>
            <td><%= reward_application.users.count %></td>
            <td><%= reward_application.created_at.to_date %></td>
            <td>
            <%= link_to '浏览', xuegongchu_reward_application_path(reward_application) %>
            <% reward_application.state_events.each do |event| %>
              <%= link_to RewardApplication.get_event_text_by(event), change_xuegongchu_reward_application_path(reward_application, shijian: event) %>
            <% end %>

            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @reward_applications %>

    </div>
  </div>
</div>


<% content_for :script do %>
  <script>
    $(function(){
      $("#xuegongchu_reward_application").addClass("active")
    })
  </script>
<% end %>

app/views/xuegongchu/reward_applications/show.html.erb
<% content_for :breadcrumb do %>
<li>
  <i class="icon-home home-icon"></i>
  <a href="<%= home_path %>">首页</a>
</li>
<li class="active">评优奖励申请浏览</li>
<% end %>

<div class="page-content">
  <div class="page-header">
    <h1>
      评优奖励申请浏览
    </h1>
  </div>

  <% if notice %>
  <div class="alert alert-block alert-success">
    <button data-dismiss="alert" class="close" type="button">
      <i class="ace-icon fa fa-times"></i>
    </button>
    <i class="ace-icon fa fa-check green"></i>
    <%= notice %>
  </div>
  <% end %>


  <div class="row">
    <div class="col-xs-12">
      <dl class="dl-horizontal">
        <dt>姓名</dt>
        <dd><%= @reward_application.user.person_info.name %></dd>
        <dt>性别</dt>
        <dd><%= @reward_application.user.person_info.gender.name %></dd>
        <dt>学号</dt>
        <dd><%= @reward_application.user.person_info.xuehao %></dd>
        <dt>专业</dt>
        <dd><%= @reward_application.user.person_info.zhuanye %></dd>
        <dt>职务</dt>
        <dd><%= @reward_application.user.person_info.zhiwu %></dd>
        <dt>政治面貌</dt>
        <dd><%= @reward_application.user.person_info.political.name %></dd>
        <dt>申请奖励</dt>
        <dd><%= @reward_application.application.try(:name) %></dd>
        <dt>联系方式</dt>
        <dd><%= @reward_application.phone %></dd>
        <dt>学院</dt>
        <dd><%= @reward_application.xueyuan.name %></dd>
        <dt>申请说明</dt>
        <dd><%= @reward_application.content %></dd>
        <dt>获得荣誉</dt>
        <dd><%= @reward_application.rongyu %></dd>
        <dt>申请状态</dt>
        <dd><%= @reward_application.state %></dd>
      </dl>
    </div>
  </div>

  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>学年</th>
          <th>学期</th>
          <th>科目</th>
          <th>成绩</th>
          <th>平均成绩</th>
          <th>操行</th>
        </tr>
      </thead>

      <tbody>
        <% @student_scores.each do |student_score| %>
          <tr>
            <td><%= student_score.xuenian.name %></td>
            <td><%= student_score.xueqi.try(:name) %></td>
            <td><%= student_score.subject.try(:name) %></td>
            <td><%= student_score.score.name %></td>
            <td><%= student_score.pingjun_score %></td>
            <td><%= student_score.caoxing %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @student_scores %>
  </div>

</div>



<% content_for :script do %>
  <script>
    $(function(){
      $("#xuegongchu_reward_application").addClass("active")
    })
  </script>
<% end %>