config/routes.rb
StudentManage::Application.routes.draw do

  resources :news, only: [:index, :show]

  namespace :admin do
    get "home" => "home#index"
    resources :zhuanyes
    resources :application_dates
    resources :news
    resources :applications
    resources :users
    resources :xueyuans
  end

  namespace :xuegongchu do
    get "home" => "home#index"
    resources :reward_applications, only: [:index, :show] do
      member do
        get :change
      end
    end
  end

  namespace :student do
    resources :reward_applications do
      member do
        get :change
        post :toupiao
      end
      collection do
        get :other
      end
    end
    resources :person_infos, except: [:index, :destroy]
    get "home" => "home#index"
    resources :scores
  end

  devise_for :users
  get "" => "home#index", as: "home"
  root to: "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :lockable, :authentication_keys => [:username]

  validates_presence_of :password, :password_confirmation
  validates :email, format: {with: RubyRegex::Email}, uniqueness: true, allow_blank: true
  validates :username, uniqueness: true
  validates :password, confirmation: true, length: {minimum: 6}

  symbolize :category, in: [:student, :admin, :xuegongchu], scopes: :shallow, methods: true

  default_value_for :category, :student

  has_many :scores, dependent: :destroy
  has_many :reward_applications, dependent: :destroy
  has_many :user_reward_applications, dependent: :destroy
  has_many :toupiao_reward_applications, through: :user_reward_applications, source: :reward_application
  has_one :person_info, dependent: :destroy

  def toupiao?(reward_application)
    toupiao_reward_applications.include?(reward_application)
  end

  def toupiao(reward_application)
    toupiao_reward_applications << reward_application
  end

  def can_toupiao?(reward_application)
    !toupiao_reward_applications.pluck(:application_id).include?(reward_application.application_id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.page(params[:page]).per_page(20)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: '用户创建成功'
    else
      render action: "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path, notice: '用户更新成功'
    else
      render action: "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :category)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="alert alert-block alert-info">
  <button data-dismiss="alert" class="close" type="button">
    <i class="ace-icon fa fa-times"></i>
  </button>
  <i class="ace-icon fa fa-check green"></i>
  密码默认为123456
</div>


<%= simple_form_for([:admin, @user], wrapper: "default-form", html: {role: "form"}) do |f| %>
  <%= f.input :username, required: true, autofocus: true, label_html: {class: "col-sm-2"} %>
  <%= f.input :password, required: true, as: :hidden, input_html: {value: "123456"} %>
  <%= f.input :password_confirmation, required: true, as: :hidden, input_html: {value: "123456"} %>
  <%= f.input :category, collection: User.get_category_values, required: true, label_html: {class: "col-sm-2"} %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-md-10">
      <%= f.button :submit, "保存", class: "btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<% content_for :breadcrumb do %>
<li>
  <i class="icon-home home-icon"></i>
  <a href="<%= home_path %>">首页</a>
</li>
<li class="active">用户编辑</li>
<% end %>

<div class="page-content">
  <div class="page-header">
    <h1>
      用户编辑
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <%= render "form" %>
    </div>
  </div>
</div>

<% content_for :script do %>
  <script>
    $(function(){
      $("#admin_user").addClass("active")
    })
  </script>
<% end %>

app/views/admin/users/index.html.erb
<% content_for :breadcrumb do %>
<li>
  <i class="icon-home home-icon"></i>
  <a href="<%= home_path %>">首页</a>
</li>
<li class="active">用户管理</li>
<% end %>

<div class="page-content">
  <div class="page-header">
    <h1>
      用户管理
      <small>
        <i class="icon-double-angle-right"></i>
        <%= link_to "添加用户", new_admin_user_path %>
      </small>
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <table class='table'>
        <tr>
          <th>用户名</th>
          <th>用户类型</th>
          <th>操作</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.category_text %></td>
          <td>
            <%= link_to "编辑", edit_admin_user_path(user) %>
            <%= link_to "删除", admin_user_path(user), confirm: "确认删除吗?", method: "delete" %>
          </td>
        </tr>
        <% end %>
      </table>

      <%= will_paginate @users %>

    </div>
  </div>
</div>



<% content_for :script do %>
  <script>
    $(function(){
      $("#admin_user").addClass("active")
    })
  </script>
<% end %>

app/views/admin/users/new.html.erb
<% content_for :breadcrumb do %>
<li>
  <i class="icon-home home-icon"></i>
  <a href="<%= home_path %>">首页</a>
</li>
<li class="active">用户添加</li>
<% end %>

<div class="page-content">
  <div class="page-header">
    <h1>
      用户添加
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <%= render "form" %>
    </div>
  </div>
</div>


<% content_for :script do %>
  <script>
    $(function(){
      $("#admin_user").addClass("active")
    })
  </script>
<% end %>

app/views/admin/users/show.html.erb
<br/>
用户名称: <%= @user.username %><br/>
用户分类: <%= @user.category_text %><br/>

<% content_for :script do %>
  <script>
    $(function(){
      $("#admin_user").addClass("active")
    })
  </script>
<% end %>